import { Injectable } from '@angular/core';
import { Amigos, Archivos, ArchivosCategoria, ArchivosEmpresa, ArchivosEstablecimiento, ArchivosEvento, ArchivosMarca, ArchivosProducto, ArchivosPromocion, Caracteristicas, CaracteristicasDeProductos, CaracteristicasEvento, CaracteristicasProducto, Categorias, Descripciones, DescripcionesEvento, DiasMes, DiasSemana, Direcciones, DireccionesPersona, Emails, EmailsPersona, Empresas, Establecimientos, Eventos, EventosEstablecimientos, FaxsPersona, Fechas, Grupos, GruposConsumicion, HorarioDiasMesEstablecimientos, HorarioDiasMesEventos, HorarioDiasMesPromociones, HorarioDiasSemanaEstablecimientos, HorarioDiasSemanaEventos, HorarioDiasSemanaPromociones, HorarioFechasEstablecimientos, HorarioFechasEventos, HorarioFechasPromociones, HorarioHorasEstablecimientos, HorarioHorasEventos, HorarioHorasPromociones, HorarioMesesEstablecimientos, HorarioMesesEventos, HorarioMesesPromociones, Horas, Invitados, LineasTicket, Marcas, MesasEstablecimiento, Meses, MiembrosGrupos, MiembrosGruposConsumicion, Paises, Personas, PersonasContactoEmpresa, PersonasContactoEstablecimiento, PersonasContactoMarcas, PersonasEstablecimientos, Productos, Promociones, PromocionesProductos, PublicidadEmpresa, PublicidadEstablecimiento, PublicidadEvento, PublicidadProducto, PublicidadPromocion, Puestos, Requisitos, RequisitosEvento, Telefonos, TelefonosPersona, Tickets, TiposCategorias, TiposEstablecimientos, TiposEventos, TiposMesas, TiposProductos, TiposPromociones, Usuarios, UsuariosRegistrandose, Ventajas, VentajasCategorias, MotivosInhabilitacion } from "@nighty/models";

@Injectable({
  providedIn: 'root'
})
export class DatosService {

  Amigos = new Array<Amigos>()
  Archivos = new Array<Archivos>()
  ArchivosCategoria = new Array<ArchivosCategoria>()
  ArchivosEmpresa = new Array<ArchivosEmpresa>()
  ArchivosEstablecimiento = new Array<ArchivosEstablecimiento>()
  ArchivosEvento = new Array<ArchivosEvento>()
  ArchivosMarca = new Array<ArchivosMarca>()
  ArchivosProducto = new Array<ArchivosProducto>()
  ArchivosPromocion = new Array<ArchivosPromocion>()
  Caracteristicas = new Array<Caracteristicas>()
  CaracteristicasDeProductos = new Array<CaracteristicasDeProductos>()
  CaracteristicasEvento = new Array<CaracteristicasEvento>()
  CaracteristicasProducto = new Array<CaracteristicasProducto>()
  Categorias = new Array<Categorias>()
  Descripciones = new Array<Descripciones>()
  DescripcionesEvento = new Array<DescripcionesEvento>()
  DiasMes = new Array<DiasMes>()
  DiasSemana = new Array<DiasSemana>()
  Direcciones = new Array<Direcciones>()
  DireccionesPersona = new Array<DireccionesPersona>()
  Emails = new Array<Emails>()
  EmailsPersona = new Array<EmailsPersona>()
  Empresas = new Array<Empresas>()
  Establecimientos = new Array<Establecimientos>()
  Eventos = new Array<Eventos>()
  EventosEstablecimientos = new Array<EventosEstablecimientos>()
  FaxsPersona = new Array<FaxsPersona>()
  Fechas = new Array<Fechas>()
  Grupos = new Array<Grupos>()
  GruposConsumicion = new Array<GruposConsumicion>()
  HorarioDiasMesEstablecimientos = new Array<HorarioDiasMesEstablecimientos>()
  HorarioDiasMesEventos = new Array<HorarioDiasMesEventos>()
  HorarioDiasMesPromociones = new Array<HorarioDiasMesPromociones>()
  HorarioDiasSemanaEstablecimientos = new Array<HorarioDiasSemanaEstablecimientos>()
  HorarioDiasSemanaEventos = new Array<HorarioDiasSemanaEventos>()
  HorarioDiasSemanaPromociones = new Array<HorarioDiasSemanaPromociones>()
  HorarioFechasEstablecimientos = new Array<HorarioFechasEstablecimientos>()
  HorarioFechasEventos = new Array<HorarioFechasEventos>()
  HorarioFechasPromociones = new Array<HorarioFechasPromociones>()
  HorarioHorasEstablecimientos = new Array<HorarioHorasEstablecimientos>()
  HorarioHorasEventos = new Array<HorarioHorasEventos>()
  HorarioHorasPromociones = new Array<HorarioHorasPromociones>()
  HorarioMesesEstablecimientos = new Array<HorarioMesesEstablecimientos>()
  HorarioMesesEventos = new Array<HorarioMesesEventos>()
  HorarioMesesPromociones = new Array<HorarioMesesPromociones>()
  Horas = new Array<Horas>()
  Invitados = new Array<Invitados>()
  LineasTicket = new Array<LineasTicket>()
  Marcas = new Array<Marcas>()
  MesasEstablecimiento = new Array<MesasEstablecimiento>()
  Meses = new Array<Meses>()
  MiembrosGrupos = new Array<MiembrosGrupos>()
  MiembrosGruposConsumicion = new Array<MiembrosGruposConsumicion>()
  MotivosInhabilitacion = new Array<MotivosInhabilitacion>()
  Paises = new Array<Paises>()
  Personas = new Array<Personas>()
  PersonasContactoEmpresa = new Array<PersonasContactoEmpresa>()
  PersonasContactoEstablecimiento = new Array<PersonasContactoEstablecimiento>()
  PersonasContactoMarcas = new Array<PersonasContactoMarcas>()
  PersonasEstablecimientos = new Array<PersonasEstablecimientos>()
  Productos = new Array<Productos>()
  Promociones = new Array<Promociones>()
  PromocionesProductos = new Array<PromocionesProductos>()
  PublicidadEmpresa = new Array<PublicidadEmpresa>()
  PublicidadEstablecimiento = new Array<PublicidadEstablecimiento>()
  PublicidadEvento = new Array<PublicidadEvento>()
  PublicidadProducto = new Array<PublicidadProducto>()
  PublicidadPromocion = new Array<PublicidadPromocion>()
  Puestos = new Array<Puestos>()
  Requisitos = new Array<Requisitos>()
  RequisitosEvento = new Array<RequisitosEvento>()
  Telefonos = new Array<Telefonos>()
  TelefonosPersona = new Array<TelefonosPersona>()
  Tickets = new Array<Tickets>()
  TiposCategorias = new Array<TiposCategorias>()
  TiposEstablecimientos = new Array<TiposEstablecimientos>()
  TiposEventos = new Array<TiposEventos>()
  TiposMesas = new Array<TiposMesas>()
  TiposProductos = new Array<TiposProductos>()
  TiposPromociones = new Array<TiposPromociones>()
  Usuarios = new Array<Usuarios>()
  UsuariosRegistrandose = new Array<UsuariosRegistrandose>()
  Ventajas = new Array<Ventajas>()
  VentajasCategorias = new Array<VentajasCategorias>()

  reiniciarAmigos = false
  reiniciarArchivos = false
  reiniciarArchivosCategoria = false
  reiniciarArchivosEmpresa = false
  reiniciarArchivosEstablecimiento = false
  reiniciarArchivosEvento = false
  reiniciarArchivosMarca = false
  reiniciarArchivosProducto = false
  reiniciarArchivosPromocion = false
  reiniciarCaracteristicas = false
  reiniciarCaracteristicasDeProductos = false
  reiniciarCaracteristicasEvento = false
  reiniciarCaracteristicasProducto = false
  reiniciarCategorias = false
  reiniciarDescripciones = false
  reiniciarDescripcionesEvento = false
  reiniciarDiasMes = false
  reiniciarDiasSemana = false
  reiniciarDirecciones = false
  reiniciarDireccionesPersona = false
  reiniciarEmails = false
  reiniciarEmailsPersona = false
  reiniciarEmpresas = false
  reiniciarEstablecimientos = false
  reiniciarEventos = false
  reiniciarEventosEstablecimientos = false
  reiniciarFaxsPersona = false
  reiniciarFechas = false
  reiniciarGrupos = false
  reiniciarGruposConsumicion = false
  reiniciarHorarioDiasMesEstablecimientos = false
  reiniciarHorarioDiasMesEventos = false
  reiniciarHorarioDiasMesPromociones = false
  reiniciarHorarioDiasSemanaEstablecimientos = false
  reiniciarHorarioDiasSemanaEventos = false
  reiniciarHorarioDiasSemanaPromociones = false
  reiniciarHorarioFechasEstablecimientos = false
  reiniciarHorarioFechasEventos = false
  reiniciarHorarioFechasPromociones = false
  reiniciarHorarioHorasEstablecimientos = false
  reiniciarHorarioHorasEventos = false
  reiniciarHorarioHorasPromociones = false
  reiniciarHorarioMesesEstablecimientos = false
  reiniciarHorarioMesesEventos = false
  reiniciarHorarioMesesPromociones = false
  reiniciarHoras = false
  reiniciarInvitados = false
  reiniciarLineasTicket = false
  reiniciarMarcas = false
  reiniciarMesasEstablecimiento = false
  reiniciarMeses = false
  reiniciarMiembrosGrupos = false
  reiniciarMiembrosGruposConsumicion = false
  reiniciarMotivosInhabilitacion = false
  reiniciarPaises = false
  reiniciarPersonas = false
  reiniciarPersonasContactoEmpresa = false
  reiniciarPersonasContactoEstablecimiento = false
  reiniciarPersonasContactoMarcas = false
  reiniciarPersonasEstablecimientos = false
  reiniciarProductos = false
  reiniciarPromociones = false
  reiniciarPromocionesProductos = false
  reiniciarPublicidadEmpresa = false
  reiniciarPublicidadEstablecimiento = false
  reiniciarPublicidadEvento = false
  reiniciarPublicidadProducto = false
  reiniciarPublicidadPromocion = false
  reiniciarPuestos = false
  reiniciarRequisitos = false
  reiniciarRequisitosEvento = false
  reiniciarTelefonos = false
  reiniciarTelefonosPersona = false
  reiniciarTickets = false
  reiniciarTiposCategorias = false
  reiniciarTiposEstablecimientos = false
  reiniciarTiposEventos = false
  reiniciarTiposMesas = false
  reiniciarTiposProductos = false
  reiniciarTiposPromociones = false
  reiniciarUsuarios = false
  reiniciarUsuariosRegistrandose = false
  reiniciarVentajas = false
  reiniciarVentajasCategorias = false

  constructor() { }
}
