use nighty;

DELETE FROM usuariosRegistrandose;
DELETE FROM tiposProductos;
DELETE FROM productos;
DELETE FROM marcas;
DELETE FROM empresas;
DELETE FROM tiposEstablecimientos;
DELETE FROM establecimientos;
DELETE FROM tiposEventos;
DELETE FROM eventos;
DELETE FROM promociones;
DELETE FROM archivos;
DELETE FROM paises;
DELETE FROM direcciones;
DELETE FROM direccionesPersona;
DELETE FROM emailsPersona;
DELETE FROM emails;
DELETE FROM telefonos;
DELETE FROM telefonosPersona;
DELETE FROM faxsPersona;
DELETE FROM horas;
DELETE FROM diasSemana;
DELETE FROM diasMes;
DELETE FROM meses;
DELETE FROM fechas;
DELETE FROM horarioHorasPromociones;
DELETE FROM horarioHorasEventos;
DELETE FROM horarioHorasEstablecimientos;
DELETE FROM horarioDiasSemanaPromociones;
DELETE FROM horarioDiasSemanaEventos;
DELETE FROM horarioDiasSemanaEstablecimientos;
DELETE FROM horarioDiasMesPromociones;
DELETE FROM horarioDiasMesEventos;
DELETE FROM horarioDiasMesEstablecimientos;
DELETE FROM horarioMesesEstablecimientos;
DELETE FROM horarioMesesPromociones;
DELETE FROM horarioMesesEventos;
DELETE FROM horarioFechasEstablecimientos;
DELETE FROM horarioFechasEventos;
DELETE FROM horarioFechasPromociones;
DELETE FROM ventajasCategorias;
DELETE FROM ventajas;
DELETE FROM puestos;
DELETE FROM personasEstablecimientos;
DELETE FROM usuarios;
DELETE FROM personas;
DELETE FROM personasContactoEmpresa;
DELETE FROM personasContactoEstablecimiento;
DELETE FROM personasContactoMarcas;
DELETE FROM caracteristicas;
DELETE FROM caracteristicasEvento;
DELETE FROM requisitos;
DELETE FROM requisitosEvento;
DELETE FROM descripciones;
DELETE FROM descripcionesEvento;
DELETE FROM eventosEstablecimientos;
DELETE FROM archivosEvento;
DELETE FROM archivosEmpresa;
DELETE FROM archivosEstablecimiento;
DELETE FROM archivosPromocion;
DELETE FROM archivosCategoria;
DELETE FROM archivosMarca;
DELETE FROM archivosProducto;
DELETE FROM tiposPromociones;
DELETE FROM promocionesProductos;
DELETE FROM caracteristicasDeProductos;
DELETE FROM caracteristicasProducto;
DELETE FROM grupos;
DELETE FROM gruposConsumicion;
DELETE FROM miembrosGrupos;
DELETE FROM miembrosGruposConsumicion;
DELETE FROM amigos;
DELETE FROM invitados;
DELETE FROM tickets;
DELETE FROM tiposMesas;
DELETE FROM mesasEstablecimiento;
DELETE FROM lineasTicket;
DELETE FROM publicidadEstablecimiento;
DELETE FROM publicidadEmpresa;
DELETE FROM publicidadProducto;
DELETE FROM publicidadEvento;
DELETE FROM publicidadPromocion;
DELETE FROM motivosInhabilitacion;
DELETE FROM categorias;
DELETE FROM tiposCategorias;
DELETE FROM chats;
DELETE FROM mensajes;

ALTER TABLE tiposProductos AUTO_INCREMENT = 1;
ALTER TABLE productos AUTO_INCREMENT = 1;
ALTER TABLE marcas AUTO_INCREMENT = 1;
ALTER TABLE empresas AUTO_INCREMENT = 1;
ALTER TABLE tiposEstablecimientos AUTO_INCREMENT = 1;
ALTER TABLE establecimientos AUTO_INCREMENT = 1;
ALTER TABLE tiposEventos AUTO_INCREMENT = 1;
ALTER TABLE eventos AUTO_INCREMENT = 1;
ALTER TABLE promociones AUTO_INCREMENT = 1;
ALTER TABLE archivos AUTO_INCREMENT = 1;
ALTER TABLE personas AUTO_INCREMENT = 1;
ALTER TABLE paises AUTO_INCREMENT = 1;
ALTER TABLE direcciones AUTO_INCREMENT = 1;
ALTER TABLE direccionesPersona AUTO_INCREMENT = 1;
ALTER TABLE emails AUTO_INCREMENT = 1;
ALTER TABLE emailsPersona AUTO_INCREMENT = 1;
ALTER TABLE telefonos AUTO_INCREMENT = 1;
ALTER TABLE telefonosPersona AUTO_INCREMENT = 1;
ALTER TABLE faxsPersona AUTO_INCREMENT = 1;
ALTER TABLE horas AUTO_INCREMENT = 1;
ALTER TABLE diasSemana AUTO_INCREMENT = 1;
ALTER TABLE diasMes AUTO_INCREMENT = 1;
ALTER TABLE meses AUTO_INCREMENT = 1;
ALTER TABLE fechas AUTO_INCREMENT = 1;
ALTER TABLE horarioHorasPromociones AUTO_INCREMENT = 1;
ALTER TABLE horarioHorasEventos AUTO_INCREMENT = 1;
ALTER TABLE horarioHorasEstablecimientos AUTO_INCREMENT = 1;
ALTER TABLE horarioDiasSemanaPromociones AUTO_INCREMENT = 1;
ALTER TABLE horarioDiasSemanaEventos AUTO_INCREMENT = 1;
ALTER TABLE horarioDiasSemanaEstablecimientos AUTO_INCREMENT = 1;
ALTER TABLE horarioDiasMesPromociones AUTO_INCREMENT = 1;
ALTER TABLE horarioDiasMesEventos AUTO_INCREMENT = 1;
ALTER TABLE horarioDiasMesEstablecimientos AUTO_INCREMENT = 1;
ALTER TABLE horarioMesesEstablecimientos AUTO_INCREMENT = 1;
ALTER TABLE horarioMesesPromociones AUTO_INCREMENT = 1;
ALTER TABLE horarioMesesEventos AUTO_INCREMENT = 1;
ALTER TABLE horarioFechasEstablecimientos AUTO_INCREMENT = 1;
ALTER TABLE horarioFechasEventos AUTO_INCREMENT = 1;
ALTER TABLE horarioFechasPromociones AUTO_INCREMENT = 1;
ALTER TABLE tiposCategorias AUTO_INCREMENT = 1;
ALTER TABLE categorias AUTO_INCREMENT = 1;
ALTER TABLE ventajasCategorias AUTO_INCREMENT = 1;
ALTER TABLE ventajas AUTO_INCREMENT = 1;
ALTER TABLE puestos AUTO_INCREMENT = 1;
ALTER TABLE personasEstablecimientos AUTO_INCREMENT = 1;
ALTER TABLE usuarios AUTO_INCREMENT = 1;
ALTER TABLE personasContactoEmpresa AUTO_INCREMENT = 1;
ALTER TABLE personasContactoEstablecimiento AUTO_INCREMENT = 1;
ALTER TABLE personasContactoMarcas AUTO_INCREMENT = 1;
ALTER TABLE caracteristicas AUTO_INCREMENT = 1;
ALTER TABLE caracteristicasEvento AUTO_INCREMENT = 1;
ALTER TABLE requisitos AUTO_INCREMENT = 1;
ALTER TABLE requisitosEvento AUTO_INCREMENT = 1;
ALTER TABLE descripciones AUTO_INCREMENT = 1;
ALTER TABLE descripcionesEvento AUTO_INCREMENT = 1;
ALTER TABLE eventosEstablecimientos AUTO_INCREMENT = 1;
ALTER TABLE archivosEvento AUTO_INCREMENT = 1;
ALTER TABLE archivosEmpresa AUTO_INCREMENT = 1;
ALTER TABLE archivosEstablecimiento AUTO_INCREMENT = 1;
ALTER TABLE archivosPromocion AUTO_INCREMENT = 1;
ALTER TABLE archivosCategoria AUTO_INCREMENT = 1;
ALTER TABLE archivosMarca AUTO_INCREMENT = 1;
ALTER TABLE archivosProducto AUTO_INCREMENT = 1;
ALTER TABLE tiposPromociones AUTO_INCREMENT = 1;
ALTER TABLE promocionesProductos AUTO_INCREMENT = 1;
ALTER TABLE caracteristicasDeProductos AUTO_INCREMENT = 1;
ALTER TABLE caracteristicasProducto AUTO_INCREMENT = 1;
ALTER TABLE grupos AUTO_INCREMENT = 1;
ALTER TABLE gruposConsumicion AUTO_INCREMENT = 1;
ALTER TABLE miembrosGrupos AUTO_INCREMENT = 1;
ALTER TABLE miembrosGruposConsumicion AUTO_INCREMENT = 1;
ALTER TABLE amigos AUTO_INCREMENT = 1;
ALTER TABLE invitados AUTO_INCREMENT = 1;
ALTER TABLE tickets AUTO_INCREMENT = 1;
ALTER TABLE tiposMesas AUTO_INCREMENT = 1;
ALTER TABLE mesasEstablecimiento AUTO_INCREMENT = 1;
ALTER TABLE lineasTicket AUTO_INCREMENT = 1;
ALTER TABLE publicidadEstablecimiento AUTO_INCREMENT = 1;
ALTER TABLE publicidadEmpresa AUTO_INCREMENT = 1;
ALTER TABLE publicidadProducto AUTO_INCREMENT = 1;
ALTER TABLE publicidadEvento AUTO_INCREMENT = 1;
ALTER TABLE publicidadPromocion AUTO_INCREMENT = 1;
ALTER TABLE publicidadPromocion AUTO_INCREMENT = 1;
ALTER TABLE motivosInhabilitacion AUTO_INCREMENT = 1;
ALTER TABLE usuariosRegistrandose AUTO_INCREMENT = 1;
ALTER TABLE chats AUTO_INCREMENT = 1;
ALTER TABLE mensajes AUTO_INCREMENT = 1;